#:schema node_modules/wrangler/config-schema.json
name = "reverse-mortgage"
main = "./.svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-01-08"


# Node.js compatibility for SvelteKit
compatibility_flags = ["nodejs_compat"]

# Build configuration
[build]
command = "pnpm run build"

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"
